# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cadc6aaf88cb503d6b02b6cef77aa2607f49ea621f20e200c9d96ab5c52ef3ebbd04c8f0c4ed24ce97d49a88a6bc2aff5b75af78e469280d83e84f9dd11b180b

test:
  secret_key_base: edc3c1ed54deadd8be0ec399908bb252f5180eb6648facbe4e9adf7673014984112f6986a9d80df4f4c864b6c89a0bea47cf5258c24fb6a05bb46172fb4bcc7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
